travis:
  secure:
    BINSTAR_TOKEN: uog7XaLU3p0IfHnauuReACv7/pLRjMirLpigfs35Whk8aMJcY/cAnyhcCKpirm3Q5mHr5/AindL+Ni0iqk52GVr5nX21R20JC4Oca5biBQRZrD/VIAB90v1wwxT58KUg33V87CUVP62zSZhOmUkFszw9Icyg+23EA22PULlPRNK1CkIyfHjhdc3N6ojspt05ZGWq6+LSXuKqRfdOvgplA78R1gyX6tS+G5up90nlsUU3etMiajBOzM5w5cVhwiwBm7OqFfl+w/AZGEYxOlahbIR8b9TDk9IPaf0G0s4fDaVkC5C/vLkGp2wSWh4gR6k8SgNxLtz6lAu3mZ0R7vBR9rooT3uyc6/JXDaUIUJsN3G/u6cUpIXHsFHtuNSsYVQsDf3BuZ5DsJf1iwH/UhedjwCPqe7Mp5ICt7FKun/1qFvGxFU7WuXFRxaS8K7yRoO6aqs0QG5MO1wgVuHIy6NWDBHtMKsJ6Y/QxlrqV4lSqP931Rl+2l/93qWIXX7F2R+xSnjfq3P477GrtPYg1Vtc7/cODKr1A6ZuTrWihZnrldEB4zd8gyX6ntB5LfY1wcqkFc2AXvLysjWflJc1EPgHEzqdSvn7E0s5yoXFtOXhRNVLZebbz1DXXXh/Xrc92XWgY8ctlZ7ad9jrHBpcoDRz/Z3jbREU1aPjt4vm5qP7NSE=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
